# Generated by Django 5.2 on 2025-04-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='starting_price',
            field=models.IntegerField(),
        ),
    ]
