# Generated by Django 5.2 on 2025-04-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='starting_price',
            field=models.CharField(max_length=7),
        ),
    ]
