# Generated by Django 5.2 on 2025-04-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_quantity_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
