# Generated by Django 5.2 on 2025-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_seller_id_item_status_alter_item_starting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
