# Generated by Django 5.2 on 2025-04-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_itemrepo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
