# Generated by Django 5.2 on 2025-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_description_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller_id',
            field=models.IntegerField(unique=True),
        ),
    ]
