# Generated by Django 5.2 on 2025-04-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
