# Generated by Django 5.2 on 2025-04-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_rename_seller_id_item_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
