# Generated by Django 5.2 on 2025-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
