# Generated by Django 5.2 on 2025-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
