# Generated by Django 5.2 on 2025-04-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_alter_reviewer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerServiceImpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
